//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bishe1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class assess1
    {
        public string type { get; set; }
        public Nullable<float> attendance { get; set; }
        public Nullable<int> requirement { get; set; }
        public Nullable<int> extra { get; set; }
        public int id { get; set; }
        public Nullable<int> self { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string loginID { get; set; }
        public Nullable<int> auditstatus { get; set; }
        public string auditID { get; set; }
        public Nullable<float> result { get; set; }
        public Nullable<float> wage { get; set; }
        public Nullable<int> backres { get; set; }
    }
}
