//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bishe1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_information
    {
        public int id { get; set; }
        public string username { get; set; }
        public string loginID { get; set; }
        public string password { get; set; }
        public int flag { get; set; }
        public string email { get; set; }
        public string qq { get; set; }
        public string tel { get; set; }
        public Nullable<System.DateTime> registertime { get; set; }
        public string type1 { get; set; }
        public string eal1 { get; set; }
        public string eal2 { get; set; }
    }
}
