//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bishe1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wage
    {
        public string type { get; set; }
        public Nullable<float> basis { get; set; }
        public Nullable<float> performance { get; set; }
        public Nullable<float> manqin { get; set; }
        public Nullable<float> craft { get; set; }
        public int id { get; set; }
    }
}
